### ISSUE TITLE
i got one error

### ISSUE THREAD

**Issue by Yossi-git** [kapenga/LittleBit#2]
when i input “java -jar e inputfile.txt out.txt”,then show me this error:

Find symbols...Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at Encoder.<init>(Encoder.java:10)
        at Encoder.bytesToSymbols(Encoder.java:234)
        at Main.main(Main.java:38)

i used jdk8

**Comment by kapenga** [comment]
Hello Yossi-git,

The default java heap space is a bit small. Too small for this program. The heap space needed is about 21 times the size of the input file. You can adjust the heap space using the attribute -Xmx. For example 'java -Xmx2048m -jar e inputfile.txt out.txt'
Try to increase this value if you keep getting this error. Or use smaller input files ;)
