### ISSUE TITLE
bugs for small file compression

### ISSUE THREAD

**Issue by da0ka** [kapenga/LittleBit#3]
encoder can't works on small file like "abcdABCDABCDabcd"

**Comment by kapenga** [comment]
Thank you for your findings. I must admit I never tested this size of files.
Currently I am not able to look into this bug report but I will fix it with the next version of LittleBit.

Edit: found the reason already. I made a stupid oversight. Changed the code locally but will not commit it yet.

**Comment by kapenga** [comment]
I did an update that should fix the bug.
